// <auto-generated />
namespace DDI.WebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserChangesForSomeUnknownReason : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserChangesForSomeUnknownReason));
        
        string IMigrationMetadata.Id
        {
            get { return "201703140507105_UserChangesForSomeUnknownReason"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
