namespace DDI.Shared.Enums
{
    public enum ModuleType
    {
        None = 0,
        GeneralLedger = 1,
        AccountsPayable = 2,
        AccountsReceivable = 3,
        FixedAssets = 4,
        Inventory = 5,
        CashProcessing = 6,
        CashDisbursements = 7,
        CashReceipting = 8,
        Donations = 9,
        NamedFunds = 10,
        CropEvents = 11,
        PlannedGiving = 12,
        Campaigns = 13,
        Investments = 14,
        LineOfCredit = 15,
        Loans = 16,
        Portfolio = 17,
        Pools = 18,
        CRM = 19,
        OfficeIntegration = 20,
        ProcessManagement = 21,
        ProjectManagement = 22,
        JobProcessing = 23,
        HealthPolicy = 24,
        SystemAdministration = 25,
        FundRaising = 26,
        ExtensionFund = 27,
        Accounting = 28,
    }
}
