namespace DDI.Data.Migrations.Client
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class RemoveIdentityFromPK : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.ConstituentAddress", "AddressId", "dbo.Address");
            DropForeignKey("dbo.Address", "AddressType_Id", "dbo.AddressType");
            DropForeignKey("dbo.ConstituentAddress", "AddressTypeId", "dbo.AddressType");
            DropForeignKey("dbo.AlternateId", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.ConstituentAddress", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.TagConstituents", "Constituent_Id", "dbo.Constituent");
            DropForeignKey("dbo.ContactInfo", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.DenominationConstituents", "Constituent_Id", "dbo.Constituent");
            DropForeignKey("dbo.DoingBusinessAs", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.Education", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.EthnicityConstituents", "Constituent_Id", "dbo.Constituent");
            DropForeignKey("dbo.PaymentPreference", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.Relationsihp", "Constituent1Id", "dbo.Constituent");
            DropForeignKey("dbo.Relationsihp", "Constituent2Id", "dbo.Constituent");
            DropForeignKey("dbo.Constituent", "ClergyStatusId", "dbo.ClergyStatus");
            DropForeignKey("dbo.Constituent", "ClergyTypeId", "dbo.ClergyType");
            DropForeignKey("dbo.Constituent", "ConstituentStatusId", "dbo.ConstituentStatus");
            DropForeignKey("dbo.TagConstituentTypes", "ConstituentType_Id", "dbo.ConstituentType");
            DropForeignKey("dbo.Constituent", "ConstituentTypeId", "dbo.ConstituentType");
            DropForeignKey("dbo.TagConstituents", "Tag_Id", "dbo.Tag");
            DropForeignKey("dbo.TagConstituentTypes", "Tag_Id", "dbo.Tag");
            DropForeignKey("dbo.Tag", "TagGroupId", "dbo.TagGroup");
            DropForeignKey("dbo.ContactCategory", "DefaultContactTypeID", "dbo.ContactType");
            DropForeignKey("dbo.ContactInfo", "ContactTypeId", "dbo.ContactType");
            DropForeignKey("dbo.ContactType", "ContactCategoryId", "dbo.ContactCategory");
            DropForeignKey("dbo.DenominationConstituents", "Denomination_Id", "dbo.Denomination");
            DropForeignKey("dbo.Constituent", "EducationLevelId", "dbo.EducationLevel");
            DropForeignKey("dbo.Education", "DegreeId", "dbo.Degree");
            DropForeignKey("dbo.Education", "SchoolId", "dbo.School");
            DropForeignKey("dbo.EthnicityConstituents", "Ethnicity_Id", "dbo.Ethnicity");
            DropForeignKey("dbo.Constituent", "GenderId", "dbo.Gender");
            DropForeignKey("dbo.Prefix", "GenderId", "dbo.Gender");
            DropForeignKey("dbo.Constituent", "IncomeLevelId", "dbo.IncomeLevel");
            DropForeignKey("dbo.Constituent", "LanguageId", "dbo.Language");
            DropForeignKey("dbo.Constituent", "PrefixId", "dbo.Prefix");
            DropForeignKey("dbo.Constituent", "ProfessionId", "dbo.Profession");
            DropForeignKey("dbo.RelationshipType", "ReciprocalTypeFemaleId", "dbo.RelationshipType");
            DropForeignKey("dbo.RelationshipType", "ReciprocalTypeMaleId", "dbo.RelationshipType");
            DropForeignKey("dbo.Relationsihp", "RelationshipTypeId", "dbo.RelationshipType");
            DropForeignKey("dbo.RelationshipType", "RelationshipCategoryId", "dbo.RelationshipCategory");
            DropForeignKey("dbo.Region", "ParentRegionId", "dbo.Region");
            DropForeignKey("dbo.Address", "Region1Id", "dbo.Region");
            DropForeignKey("dbo.Address", "Region2Id", "dbo.Region");
            DropForeignKey("dbo.Address", "Region3Id", "dbo.Region");
            DropForeignKey("dbo.Address", "Region4Id", "dbo.Region");
            DropForeignKey("dbo.RegionArea", "RegionId", "dbo.Region");
            DropPrimaryKey("dbo.Address");
            DropPrimaryKey("dbo.ConstituentAddress");
            DropPrimaryKey("dbo.AddressType");
            DropPrimaryKey("dbo.Constituent");
            DropPrimaryKey("dbo.AlternateId");
            DropPrimaryKey("dbo.ClergyStatus");
            DropPrimaryKey("dbo.ClergyType");
            DropPrimaryKey("dbo.ConstituentStatus");
            DropPrimaryKey("dbo.ConstituentType");
            DropPrimaryKey("dbo.Tag");
            DropPrimaryKey("dbo.TagGroup");
            DropPrimaryKey("dbo.ContactInfo");
            DropPrimaryKey("dbo.ContactType");
            DropPrimaryKey("dbo.ContactCategory");
            DropPrimaryKey("dbo.Denomination");
            DropPrimaryKey("dbo.DoingBusinessAs");
            DropPrimaryKey("dbo.EducationLevel");
            DropPrimaryKey("dbo.Education");
            DropPrimaryKey("dbo.Degree");
            DropPrimaryKey("dbo.School");
            DropPrimaryKey("dbo.Ethnicity");
            DropPrimaryKey("dbo.Gender");
            DropPrimaryKey("dbo.IncomeLevel");
            DropPrimaryKey("dbo.Language");
            DropPrimaryKey("dbo.PaymentPreference");
            DropPrimaryKey("dbo.Prefix");
            DropPrimaryKey("dbo.Profession");
            DropPrimaryKey("dbo.Relationsihp");
            DropPrimaryKey("dbo.RelationshipType");
            DropPrimaryKey("dbo.RelationshipCategory");
            DropPrimaryKey("dbo.Region");
            DropPrimaryKey("dbo.RegionArea");
            DropPrimaryKey("dbo.LogEntry");
            DropPrimaryKey("dbo.MaritialStatus");
            DropPrimaryKey("dbo.RegionLevel");
            DropPrimaryKey("dbo.SectionPreference");
            AlterColumn("dbo.Address", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ConstituentAddress", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.AddressType", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Constituent", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.AlternateId", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClergyStatus", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ClergyType", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ConstituentStatus", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ConstituentType", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Tag", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.TagGroup", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ContactInfo", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ContactType", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.ContactCategory", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Denomination", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.DoingBusinessAs", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.EducationLevel", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Education", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Degree", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.School", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Ethnicity", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Gender", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.IncomeLevel", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Language", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.PaymentPreference", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Prefix", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Profession", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Relationsihp", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.RelationshipType", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.RelationshipCategory", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Region", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.RegionArea", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.LogEntry", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.MaritialStatus", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.RegionLevel", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.SectionPreference", "Id", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.Address", "Id");
            AddPrimaryKey("dbo.ConstituentAddress", "Id");
            AddPrimaryKey("dbo.AddressType", "Id");
            AddPrimaryKey("dbo.Constituent", "Id");
            AddPrimaryKey("dbo.AlternateId", "Id");
            AddPrimaryKey("dbo.ClergyStatus", "Id");
            AddPrimaryKey("dbo.ClergyType", "Id");
            AddPrimaryKey("dbo.ConstituentStatus", "Id");
            AddPrimaryKey("dbo.ConstituentType", "Id");
            AddPrimaryKey("dbo.Tag", "Id");
            AddPrimaryKey("dbo.TagGroup", "Id");
            AddPrimaryKey("dbo.ContactInfo", "Id");
            AddPrimaryKey("dbo.ContactType", "Id");
            AddPrimaryKey("dbo.ContactCategory", "Id");
            AddPrimaryKey("dbo.Denomination", "Id");
            AddPrimaryKey("dbo.DoingBusinessAs", "Id");
            AddPrimaryKey("dbo.EducationLevel", "Id");
            AddPrimaryKey("dbo.Education", "Id");
            AddPrimaryKey("dbo.Degree", "Id");
            AddPrimaryKey("dbo.School", "Id");
            AddPrimaryKey("dbo.Ethnicity", "Id");
            AddPrimaryKey("dbo.Gender", "Id");
            AddPrimaryKey("dbo.IncomeLevel", "Id");
            AddPrimaryKey("dbo.Language", "Id");
            AddPrimaryKey("dbo.PaymentPreference", "Id");
            AddPrimaryKey("dbo.Prefix", "Id");
            AddPrimaryKey("dbo.Profession", "Id");
            AddPrimaryKey("dbo.Relationsihp", "Id");
            AddPrimaryKey("dbo.RelationshipType", "Id");
            AddPrimaryKey("dbo.RelationshipCategory", "Id");
            AddPrimaryKey("dbo.Region", "Id");
            AddPrimaryKey("dbo.RegionArea", "Id");
            AddPrimaryKey("dbo.LogEntry", "Id");
            AddPrimaryKey("dbo.MaritialStatus", "Id");
            AddPrimaryKey("dbo.RegionLevel", "Id");
            AddPrimaryKey("dbo.SectionPreference", "Id");
            AddForeignKey("dbo.ConstituentAddress", "AddressId", "dbo.Address", "Id");
            AddForeignKey("dbo.Address", "AddressType_Id", "dbo.AddressType", "Id");
            AddForeignKey("dbo.ConstituentAddress", "AddressTypeId", "dbo.AddressType", "Id");
            AddForeignKey("dbo.AlternateId", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.ConstituentAddress", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.TagConstituents", "Constituent_Id", "dbo.Constituent", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ContactInfo", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.DenominationConstituents", "Constituent_Id", "dbo.Constituent", "Id", cascadeDelete: true);
            AddForeignKey("dbo.DoingBusinessAs", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.Education", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.EthnicityConstituents", "Constituent_Id", "dbo.Constituent", "Id", cascadeDelete: true);
            AddForeignKey("dbo.PaymentPreference", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.Relationsihp", "Constituent1Id", "dbo.Constituent", "Id");
            AddForeignKey("dbo.Relationsihp", "Constituent2Id", "dbo.Constituent", "Id");
            AddForeignKey("dbo.Constituent", "ClergyStatusId", "dbo.ClergyStatus", "Id");
            AddForeignKey("dbo.Constituent", "ClergyTypeId", "dbo.ClergyType", "Id");
            AddForeignKey("dbo.Constituent", "ConstituentStatusId", "dbo.ConstituentStatus", "Id");
            AddForeignKey("dbo.TagConstituentTypes", "ConstituentType_Id", "dbo.ConstituentType", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Constituent", "ConstituentTypeId", "dbo.ConstituentType", "Id");
            AddForeignKey("dbo.TagConstituents", "Tag_Id", "dbo.Tag", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TagConstituentTypes", "Tag_Id", "dbo.Tag", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Tag", "TagGroupId", "dbo.TagGroup", "Id");
            AddForeignKey("dbo.ContactCategory", "DefaultContactTypeID", "dbo.ContactType", "Id");
            AddForeignKey("dbo.ContactInfo", "ContactTypeId", "dbo.ContactType", "Id");
            AddForeignKey("dbo.ContactType", "ContactCategoryId", "dbo.ContactCategory", "Id");
            AddForeignKey("dbo.DenominationConstituents", "Denomination_Id", "dbo.Denomination", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Constituent", "EducationLevelId", "dbo.EducationLevel", "Id");
            AddForeignKey("dbo.Education", "DegreeId", "dbo.Degree", "Id");
            AddForeignKey("dbo.Education", "SchoolId", "dbo.School", "Id");
            AddForeignKey("dbo.EthnicityConstituents", "Ethnicity_Id", "dbo.Ethnicity", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Constituent", "GenderId", "dbo.Gender", "Id");
            AddForeignKey("dbo.Prefix", "GenderId", "dbo.Gender", "Id");
            AddForeignKey("dbo.Constituent", "IncomeLevelId", "dbo.IncomeLevel", "Id");
            AddForeignKey("dbo.Constituent", "LanguageId", "dbo.Language", "Id");
            AddForeignKey("dbo.Constituent", "PrefixId", "dbo.Prefix", "Id");
            AddForeignKey("dbo.Constituent", "ProfessionId", "dbo.Profession", "Id");
            AddForeignKey("dbo.RelationshipType", "ReciprocalTypeFemaleId", "dbo.RelationshipType", "Id");
            AddForeignKey("dbo.RelationshipType", "ReciprocalTypeMaleId", "dbo.RelationshipType", "Id");
            AddForeignKey("dbo.Relationsihp", "RelationshipTypeId", "dbo.RelationshipType", "Id");
            AddForeignKey("dbo.RelationshipType", "RelationshipCategoryId", "dbo.RelationshipCategory", "Id");
            AddForeignKey("dbo.Region", "ParentRegionId", "dbo.Region", "Id");
            AddForeignKey("dbo.Address", "Region1Id", "dbo.Region", "Id");
            AddForeignKey("dbo.Address", "Region2Id", "dbo.Region", "Id");
            AddForeignKey("dbo.Address", "Region3Id", "dbo.Region", "Id");
            AddForeignKey("dbo.Address", "Region4Id", "dbo.Region", "Id");
            AddForeignKey("dbo.RegionArea", "RegionId", "dbo.Region", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.RegionArea", "RegionId", "dbo.Region");
            DropForeignKey("dbo.Address", "Region4Id", "dbo.Region");
            DropForeignKey("dbo.Address", "Region3Id", "dbo.Region");
            DropForeignKey("dbo.Address", "Region2Id", "dbo.Region");
            DropForeignKey("dbo.Address", "Region1Id", "dbo.Region");
            DropForeignKey("dbo.Region", "ParentRegionId", "dbo.Region");
            DropForeignKey("dbo.RelationshipType", "RelationshipCategoryId", "dbo.RelationshipCategory");
            DropForeignKey("dbo.Relationsihp", "RelationshipTypeId", "dbo.RelationshipType");
            DropForeignKey("dbo.RelationshipType", "ReciprocalTypeMaleId", "dbo.RelationshipType");
            DropForeignKey("dbo.RelationshipType", "ReciprocalTypeFemaleId", "dbo.RelationshipType");
            DropForeignKey("dbo.Constituent", "ProfessionId", "dbo.Profession");
            DropForeignKey("dbo.Constituent", "PrefixId", "dbo.Prefix");
            DropForeignKey("dbo.Constituent", "LanguageId", "dbo.Language");
            DropForeignKey("dbo.Constituent", "IncomeLevelId", "dbo.IncomeLevel");
            DropForeignKey("dbo.Prefix", "GenderId", "dbo.Gender");
            DropForeignKey("dbo.Constituent", "GenderId", "dbo.Gender");
            DropForeignKey("dbo.EthnicityConstituents", "Ethnicity_Id", "dbo.Ethnicity");
            DropForeignKey("dbo.Education", "SchoolId", "dbo.School");
            DropForeignKey("dbo.Education", "DegreeId", "dbo.Degree");
            DropForeignKey("dbo.Constituent", "EducationLevelId", "dbo.EducationLevel");
            DropForeignKey("dbo.DenominationConstituents", "Denomination_Id", "dbo.Denomination");
            DropForeignKey("dbo.ContactType", "ContactCategoryId", "dbo.ContactCategory");
            DropForeignKey("dbo.ContactInfo", "ContactTypeId", "dbo.ContactType");
            DropForeignKey("dbo.ContactCategory", "DefaultContactTypeID", "dbo.ContactType");
            DropForeignKey("dbo.Tag", "TagGroupId", "dbo.TagGroup");
            DropForeignKey("dbo.TagConstituentTypes", "Tag_Id", "dbo.Tag");
            DropForeignKey("dbo.TagConstituents", "Tag_Id", "dbo.Tag");
            DropForeignKey("dbo.Constituent", "ConstituentTypeId", "dbo.ConstituentType");
            DropForeignKey("dbo.TagConstituentTypes", "ConstituentType_Id", "dbo.ConstituentType");
            DropForeignKey("dbo.Constituent", "ConstituentStatusId", "dbo.ConstituentStatus");
            DropForeignKey("dbo.Constituent", "ClergyTypeId", "dbo.ClergyType");
            DropForeignKey("dbo.Constituent", "ClergyStatusId", "dbo.ClergyStatus");
            DropForeignKey("dbo.Relationsihp", "Constituent2Id", "dbo.Constituent");
            DropForeignKey("dbo.Relationsihp", "Constituent1Id", "dbo.Constituent");
            DropForeignKey("dbo.PaymentPreference", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.EthnicityConstituents", "Constituent_Id", "dbo.Constituent");
            DropForeignKey("dbo.Education", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.DoingBusinessAs", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.DenominationConstituents", "Constituent_Id", "dbo.Constituent");
            DropForeignKey("dbo.ContactInfo", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.TagConstituents", "Constituent_Id", "dbo.Constituent");
            DropForeignKey("dbo.ConstituentAddress", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.AlternateId", "ConstituentId", "dbo.Constituent");
            DropForeignKey("dbo.ConstituentAddress", "AddressTypeId", "dbo.AddressType");
            DropForeignKey("dbo.Address", "AddressType_Id", "dbo.AddressType");
            DropForeignKey("dbo.ConstituentAddress", "AddressId", "dbo.Address");
            DropPrimaryKey("dbo.SectionPreference");
            DropPrimaryKey("dbo.RegionLevel");
            DropPrimaryKey("dbo.MaritialStatus");
            DropPrimaryKey("dbo.LogEntry");
            DropPrimaryKey("dbo.RegionArea");
            DropPrimaryKey("dbo.Region");
            DropPrimaryKey("dbo.RelationshipCategory");
            DropPrimaryKey("dbo.RelationshipType");
            DropPrimaryKey("dbo.Relationsihp");
            DropPrimaryKey("dbo.Profession");
            DropPrimaryKey("dbo.Prefix");
            DropPrimaryKey("dbo.PaymentPreference");
            DropPrimaryKey("dbo.Language");
            DropPrimaryKey("dbo.IncomeLevel");
            DropPrimaryKey("dbo.Gender");
            DropPrimaryKey("dbo.Ethnicity");
            DropPrimaryKey("dbo.School");
            DropPrimaryKey("dbo.Degree");
            DropPrimaryKey("dbo.Education");
            DropPrimaryKey("dbo.EducationLevel");
            DropPrimaryKey("dbo.DoingBusinessAs");
            DropPrimaryKey("dbo.Denomination");
            DropPrimaryKey("dbo.ContactCategory");
            DropPrimaryKey("dbo.ContactType");
            DropPrimaryKey("dbo.ContactInfo");
            DropPrimaryKey("dbo.TagGroup");
            DropPrimaryKey("dbo.Tag");
            DropPrimaryKey("dbo.ConstituentType");
            DropPrimaryKey("dbo.ConstituentStatus");
            DropPrimaryKey("dbo.ClergyType");
            DropPrimaryKey("dbo.ClergyStatus");
            DropPrimaryKey("dbo.AlternateId");
            DropPrimaryKey("dbo.Constituent");
            DropPrimaryKey("dbo.AddressType");
            DropPrimaryKey("dbo.ConstituentAddress");
            DropPrimaryKey("dbo.Address");
            AlterColumn("dbo.SectionPreference", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.RegionLevel", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.MaritialStatus", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.LogEntry", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.RegionArea", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Region", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.RelationshipCategory", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.RelationshipType", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Relationsihp", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Profession", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Prefix", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.PaymentPreference", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Language", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.IncomeLevel", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Gender", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Ethnicity", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.School", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Degree", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Education", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.EducationLevel", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.DoingBusinessAs", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Denomination", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.ContactCategory", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.ContactType", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.ContactInfo", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.TagGroup", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Tag", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.ConstituentType", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.ConstituentStatus", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.ClergyType", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.ClergyStatus", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.AlternateId", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Constituent", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.AddressType", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.ConstituentAddress", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Address", "Id", c => c.Guid(nullable: false, identity: true));
            AddPrimaryKey("dbo.SectionPreference", "Id");
            AddPrimaryKey("dbo.RegionLevel", "Id");
            AddPrimaryKey("dbo.MaritialStatus", "Id");
            AddPrimaryKey("dbo.LogEntry", "Id");
            AddPrimaryKey("dbo.RegionArea", "Id");
            AddPrimaryKey("dbo.Region", "Id");
            AddPrimaryKey("dbo.RelationshipCategory", "Id");
            AddPrimaryKey("dbo.RelationshipType", "Id");
            AddPrimaryKey("dbo.Relationsihp", "Id");
            AddPrimaryKey("dbo.Profession", "Id");
            AddPrimaryKey("dbo.Prefix", "Id");
            AddPrimaryKey("dbo.PaymentPreference", "Id");
            AddPrimaryKey("dbo.Language", "Id");
            AddPrimaryKey("dbo.IncomeLevel", "Id");
            AddPrimaryKey("dbo.Gender", "Id");
            AddPrimaryKey("dbo.Ethnicity", "Id");
            AddPrimaryKey("dbo.School", "Id");
            AddPrimaryKey("dbo.Degree", "Id");
            AddPrimaryKey("dbo.Education", "Id");
            AddPrimaryKey("dbo.EducationLevel", "Id");
            AddPrimaryKey("dbo.DoingBusinessAs", "Id");
            AddPrimaryKey("dbo.Denomination", "Id");
            AddPrimaryKey("dbo.ContactCategory", "Id");
            AddPrimaryKey("dbo.ContactType", "Id");
            AddPrimaryKey("dbo.ContactInfo", "Id");
            AddPrimaryKey("dbo.TagGroup", "Id");
            AddPrimaryKey("dbo.Tag", "Id");
            AddPrimaryKey("dbo.ConstituentType", "Id");
            AddPrimaryKey("dbo.ConstituentStatus", "Id");
            AddPrimaryKey("dbo.ClergyType", "Id");
            AddPrimaryKey("dbo.ClergyStatus", "Id");
            AddPrimaryKey("dbo.AlternateId", "Id");
            AddPrimaryKey("dbo.Constituent", "Id");
            AddPrimaryKey("dbo.AddressType", "Id");
            AddPrimaryKey("dbo.ConstituentAddress", "Id");
            AddPrimaryKey("dbo.Address", "Id");
            AddForeignKey("dbo.RegionArea", "RegionId", "dbo.Region", "Id");
            AddForeignKey("dbo.Address", "Region4Id", "dbo.Region", "Id");
            AddForeignKey("dbo.Address", "Region3Id", "dbo.Region", "Id");
            AddForeignKey("dbo.Address", "Region2Id", "dbo.Region", "Id");
            AddForeignKey("dbo.Address", "Region1Id", "dbo.Region", "Id");
            AddForeignKey("dbo.Region", "ParentRegionId", "dbo.Region", "Id");
            AddForeignKey("dbo.RelationshipType", "RelationshipCategoryId", "dbo.RelationshipCategory", "Id");
            AddForeignKey("dbo.Relationsihp", "RelationshipTypeId", "dbo.RelationshipType", "Id");
            AddForeignKey("dbo.RelationshipType", "ReciprocalTypeMaleId", "dbo.RelationshipType", "Id");
            AddForeignKey("dbo.RelationshipType", "ReciprocalTypeFemaleId", "dbo.RelationshipType", "Id");
            AddForeignKey("dbo.Constituent", "ProfessionId", "dbo.Profession", "Id");
            AddForeignKey("dbo.Constituent", "PrefixId", "dbo.Prefix", "Id");
            AddForeignKey("dbo.Constituent", "LanguageId", "dbo.Language", "Id");
            AddForeignKey("dbo.Constituent", "IncomeLevelId", "dbo.IncomeLevel", "Id");
            AddForeignKey("dbo.Prefix", "GenderId", "dbo.Gender", "Id");
            AddForeignKey("dbo.Constituent", "GenderId", "dbo.Gender", "Id");
            AddForeignKey("dbo.EthnicityConstituents", "Ethnicity_Id", "dbo.Ethnicity", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Education", "SchoolId", "dbo.School", "Id");
            AddForeignKey("dbo.Education", "DegreeId", "dbo.Degree", "Id");
            AddForeignKey("dbo.Constituent", "EducationLevelId", "dbo.EducationLevel", "Id");
            AddForeignKey("dbo.DenominationConstituents", "Denomination_Id", "dbo.Denomination", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ContactType", "ContactCategoryId", "dbo.ContactCategory", "Id");
            AddForeignKey("dbo.ContactInfo", "ContactTypeId", "dbo.ContactType", "Id");
            AddForeignKey("dbo.ContactCategory", "DefaultContactTypeID", "dbo.ContactType", "Id");
            AddForeignKey("dbo.Tag", "TagGroupId", "dbo.TagGroup", "Id");
            AddForeignKey("dbo.TagConstituentTypes", "Tag_Id", "dbo.Tag", "Id", cascadeDelete: true);
            AddForeignKey("dbo.TagConstituents", "Tag_Id", "dbo.Tag", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Constituent", "ConstituentTypeId", "dbo.ConstituentType", "Id");
            AddForeignKey("dbo.TagConstituentTypes", "ConstituentType_Id", "dbo.ConstituentType", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Constituent", "ConstituentStatusId", "dbo.ConstituentStatus", "Id");
            AddForeignKey("dbo.Constituent", "ClergyTypeId", "dbo.ClergyType", "Id");
            AddForeignKey("dbo.Constituent", "ClergyStatusId", "dbo.ClergyStatus", "Id");
            AddForeignKey("dbo.Relationsihp", "Constituent2Id", "dbo.Constituent", "Id");
            AddForeignKey("dbo.Relationsihp", "Constituent1Id", "dbo.Constituent", "Id");
            AddForeignKey("dbo.PaymentPreference", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.EthnicityConstituents", "Constituent_Id", "dbo.Constituent", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Education", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.DoingBusinessAs", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.DenominationConstituents", "Constituent_Id", "dbo.Constituent", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ContactInfo", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.TagConstituents", "Constituent_Id", "dbo.Constituent", "Id", cascadeDelete: true);
            AddForeignKey("dbo.ConstituentAddress", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.AlternateId", "ConstituentId", "dbo.Constituent", "Id");
            AddForeignKey("dbo.ConstituentAddress", "AddressTypeId", "dbo.AddressType", "Id");
            AddForeignKey("dbo.Address", "AddressType_Id", "dbo.AddressType", "Id");
            AddForeignKey("dbo.ConstituentAddress", "AddressId", "dbo.Address", "Id");
        }
    }
}
