// <auto-generated />
namespace DDI.Data.Migrations.Client
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Auditing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Auditing));
        
        string IMigrationMetadata.Id
        {
            get { return "201702271742325_Auditing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
